root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "make build-and-swagger"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs", "bin", "logs", "monitoring", "scripts", "static"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*\\.md$", ".*\\.json$", ".*\\.yaml$", ".*\\.yml$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal"]
  include_ext = ["go"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  pre_cmd = []
  post_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false
  # FAIL HARD on compilation errors - don't run broken code
  # This ensures we don't run old versions when new code has syntax errors
  stop_on_err = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true 